server:
  port: 8081

logging:
  level:
    root: WARN
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.boot.security: DEBUG

spring:
  datasource:
      url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

jwt:
  secret: sign
  expire: 300 #second